version: '3'
services:
  web:
    build:
      context: ../../../
      dockerfile: ./src/infra/docker/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    restart: unless-stopped
    volumes:
      - ./postgres-uuid-ossp.sh:/docker-entrypoint-initdb.d/postgres-uuid-ossp.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nuplant
    ports:
      - "5432:5432"
